# # This file should contain all the record creation needed to seed the database with its default values.
# # The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
# #
# # Examples:
# #
# #   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
# #   Character.create(name: 'Luke', movie: movies.first)

# Duration.create(length: "Short")
# Duration.create(length: "Medium")
# Duration.create(length: "Long")

# AgeGroup.create(age_category: "Kids")
# AgeGroup.create(age_category: "Teens")
# AgeGroup.create(age_category: "Young Adults")
# AgeGroup.create(age_category: "Adults")

# Category.create(genre: "History")
# Category.create(genre: "Geography")
# Category.create(genre: "Technology")
# Category.create(genre: "Medical Science")
# Category.create(genre: "Politics")
# Category.create(genre: "Business")
# Category.create(genre: "Ethics")
# Category.create(genre: "Creative Writing")
# Category.create(genre: "Psychology")
# Category.create(genre: "Self-Help")
# Category.create(genre: "Curiosity")

EducatorProfile.create(name: "Kristin Robijn Terpstra", description: "Host of The History Cache podcast.", photo_url: "https://cachedimages.podchaser.com/300x300/aHR0cHM6Ly9jcmVhdG9yLWltYWdlcy5wb2RjaGFzZXIuY29tLzk3ZDhjZWE4MDVkNjA4ODk4MWVjMWI2M2VlMGEzNjAxLmpwZWc%3D/aHR0cHM6Ly93d3cucG9kY2hhc2VyLmNvbS9pbWFnZXMvbWlzc2luZy1pbWFnZS5wbmc%3D")

Podcast.create(educator_profile_id: 1, podcast_title: "The History Cache Podcast", date: "Sep 11th 2019", podcast_photo: "https://cachedimages.podchaser.com/300x300/aHR0cHM6Ly9wYmNkbjEucG9kYmVhbi5jb20vaW1nbG9nby9pbWFnZS1sb2dvLzU4NzEwODYvQXBwbGVTdGFuZGFyZExvZ28ucG5n/aHR0cHM6Ly93d3cucG9kY2hhc2VyLmNvbS9pbWFnZXMvbWlzc2luZy1pbWFnZS5wbmc%3D", episode_no: "3", episode_name: "History Byte: Rocket Man Was a Monkey: Animal Astronauts of the Final Frontier", actual_length: "27m 2s", url: "https://mcdn.podbean.com/mf/web/smb46e/HB2_Animal_Astronauts_Final.mp3", category: "History", age_group: "Young Adults", duration: "Long", description: "Come and meet Ham the astronaut chimp and discover how the animal astronauts of history just may have saved us all. Also featuring Space Dogs and one phenomenal Astro Cat for an episode that's literally out of this world.")

Podcast.create(educator_profile_id: 1, podcast_title: "The History Cache Podcast", date: "Oct 16th 2019", podcast_photo: "https://cachedimages.podchaser.com/300x300/aHR0cHM6Ly9wYmNkbjEucG9kYmVhbi5jb20vaW1nbG9nby9pbWFnZS1sb2dvLzU4NzEwODYvQXBwbGVTdGFuZGFyZExvZ28ucG5n/aHR0cHM6Ly93d3cucG9kY2hhc2VyLmNvbS9pbWFnZXMvbWlzc2luZy1pbWFnZS5wbmc%3D", episode_no: "4", episode_name: "History Byte: The First Monsters", actual_length: "27m 2s", url: "https://mcdn.podbean.com/mf/web/n8xmux/The_First_Monsters_Final.mp3", category: "History", age_group: "Young Adults, Kids", duration: "Long", description: "Come and meet Ham the astronaut chimp and discover how the animal astronauts of history just may have saved us all. Also featuring Space Dogs and one phenomenal Astro Cat for an episode that's literally out of this world.")

EducatorProfile.create(name: "Rohith Amruthur", description: "Ever since he was a child, Rohith was always fascinated by geography and learning about other cultures. He would sit for hours and read maps and atlases, and even draw his own. While he looked at and read these maps, he became naturally curious as to what life was like around the world. His passion for geography as a child left him quite gifted with the subject and he consistently participated in the National Geographic Bee contest in elementary and middle schools. He was able to travel to many different places around the world including plenty of states within the USA, India, Malaysia, Singapore, Germany, the Netherlands, the Bahamas, Canada, Austria, Spain, and Poland.", photo_url: "https://cachedimages.podchaser.com/300x300/aHR0cHM6Ly9jcmVhdG9yLWltYWdlcy5wb2RjaGFzZXIuY29tLzA5YzVhYzljZWVhZjVlNjRjMzg5OWY4OWZjODE5NmQxLmpwZWc%3D/aHR0cHM6Ly93d3cucG9kY2hhc2VyLmNvbS9pbWFnZXMvbWlzc2luZy1pbWFnZS5wbmc%3D")

Podcast.create(educator_profile_id: 2, podcast_title: "The Lost Geographer Podcast", date: "May 24th 2016", podcast_photo: "https://cachedimages.podchaser.com/x200/aHR0cDovL3N0YXRpYy5saWJzeW4uY29tL3AvYXNzZXRzLzAvNi82L2UvMDY2ZTY3NjI2OGY3YTQwYS9Qb2RjYXN0LnBuZw%3D%3D/aHR0cHM6Ly93d3cucG9kY2hhc2VyLmNvbS9pbWFnZXMvbWlzc2luZy1pbWFnZS5wbmc%3D", episode_no: "1", episode_name: "Episode 1 - Introduction to The Lost Geographer Podcast", actual_length: "27m 2s", url: "http://traffic.libsyn.com/thelostgeographer/Ep_1_final.mp3", category: "Geography", age_group: "Young Adults, Teens", duration: "Medium", description: "This is the first episode of The Lost Geographer Podcast. Here, you will understand the goal of the podcast and what you can expect from future episodes. In this modern world, it is important to be geographically and culturally literate, and to understand the way human interact so that we can make the world a better place, one interaction at a time.")

Podcast.create(educator_profile_id: 2, podcast_title: "The Lost Geographer Podcast", date: "August 20th 2019", podcast_photo: "https://cachedimages.podchaser.com/x200/aHR0cDovL3N0YXRpYy5saWJzeW4uY29tL3AvYXNzZXRzLzAvNi82L2UvMDY2ZTY3NjI2OGY3YTQwYS9Qb2RjYXN0LnBuZw%3D%3D/aHR0cHM6Ly93d3cucG9kY2hhc2VyLmNvbS9pbWFnZXMvbWlzc2luZy1pbWFnZS5wbmc%3D", episode_no: "131", episode_name: "Egypt", actual_length: "1h 3m", url: "http://hwcdn.libsyn.com/p/3/2/0/320a11482abd2974/Ep131_final.mp3?c_id=49758869&cs_id=49758869&destination_id=385503&expiration=1575471117&hwt=6f0813322df2430de52554dd8ac9bc6b", category: "Geography", age_group: "Young Adults, Teens, Kids, Adults", duration: "Long", description: "Ready to learn about one of the oldest civilizations in the world? A civilization so ancient, that there's even a field of study surrounding it (Egyptology). Tune in to learn more about Egypt, both ancient and contemporary!
")

EducatorProfile.create(name: "Alex Goldman", description: "Alex Goldman is co-host of Reply All. His work has appeared on On the Media, 99% Invisible, Slate, and elsewhere.", photo_url: "https://cachedimages.podchaser.com/300x300/aHR0cHM6Ly9jcmVhdG9yLWltYWdlcy5wb2RjaGFzZXIuY29tLzU4NmYxZDA1MDgwYTMwOWU5NGM5OWQ5ZDc5OWJjNGQzLnBuZw%3D%3D/aHR0cHM6Ly93d3cucG9kY2hhc2VyLmNvbS9pbWFnZXMvbWlzc2luZy1pbWFnZS5wbmc%3D")

Podcast.create(educator_profile_id: 3, podcast_title: "Reply All", date: "November 14th 2019", podcast_photo: "https://cachedimages.podchaser.com/300x300/aHR0cHM6Ly9tZWdhcGhvbmUtcHJvZC5zMy5hbWF6b25hd3MuY29tL3BvZGNhc3RzLzA1ZjcxNzQ2LWE4MjUtMTFlNS1hZWI1LWE3YTU3MmRmNTc1ZS9pbWFnZS91cGxvYWRzXzJGMTU2OTkwMTc5OTQ1NS1pd3poY3l0dWx0LTIzZTQyNTkxNDYwN2IzNDJhN2I4YWFhZWZlYmY4MDA1XzJGUmVwbHlBbGxfMDkzMDE5LmpwZw%3D%3D/aHR0cHM6Ly93d3cucG9kY2hhc2VyLmNvbS9pbWFnZXMvbWlzc2luZy1pbWFnZS5wbmc%3D", episode_no: "151", episode_name: "Thank You for Noticing", actual_length: "50m 10s", url: "https://dcs.megaphone.fm/GLT5362914806.mp3", category: "Technology, Fantasy", age_group: "Kids, Young Adults, Teens", duration: "Long", description: "A listener finds a UFO floating in the sky over a leather store, and Alex sets out to find the man who put it there.")

Podcast.create(educator_profile_id: 3, podcast_title: "Reply All", date: "November 8th 2019", podcast_photo: "https://cachedimages.podchaser.com/300x300/aHR0cHM6Ly9tZWdhcGhvbmUtcHJvZC5zMy5hbWF6b25hd3MuY29tL3BvZGNhc3RzLzA1ZjcxNzQ2LWE4MjUtMTFlNS1hZWI1LWE3YTU3MmRmNTc1ZS9pbWFnZS91cGxvYWRzXzJGMTU2OTkwMTc5OTQ1NS1pd3poY3l0dWx0LTIzZTQyNTkxNDYwN2IzNDJhN2I4YWFhZWZlYmY4MDA1XzJGUmVwbHlBbGxfMDkzMDE5LmpwZw%3D%3D/aHR0cHM6Ly93d3cucG9kY2hhc2VyLmNvbS9pbWFnZXMvbWlzc2luZy1pbWFnZS5wbmc%3D", episode_no: "130", episode_name: "The Snapchat Thief", actual_length: "1h 10m", url: "https://dcs.megaphone.fm/GLT8967905844.mp3", category: "Technology, Social Media", age_group: "Young Adults, Teens, Adults", duration: "Long", description: "This week, a new Super Tech Support: after Lizzie's Snapchat gets hacked, things start getting really creepy. Alex investigates.")

EducatorProfile.create(name: "Peter Attia", description: "Dr. Peter Attia, a Stanford/Johns Hopkins/NIH-trained physician focusing on the applied science of longevity, the extension of human life and well-being.", photo_url: "https://peterattiamd.com/wp-content/uploads/2019/10/Peter-Attia-C57A2508.jpg")

Podcast.create(educator_profile_id: 4, podcast_title: "The Peter Attia Drive", date: "November 25th 2019", podcast_photo: "https://cachedimages.podchaser.com/x200/aHR0cDovL3N0YXRpYy5saWJzeW4uY29tL3AvYXNzZXRzL2IvNy84L2YvYjc4ZmM1MDgyNmNhNDQ3Yy9FUC44MV8tX1N0ZXZlX0dvbGRuZXJfYW5kX0RlYnJhX0tpbWxlc3NfRklOQUwucG5n/aHR0cHM6Ly93d3cucG9kY2hhc2VyLmNvbS9pbWFnZXMvbWlzc2luZy1pbWFnZS5wbmc%3D", episode_no: "151", episode_name: "#81 - Debra Kimless, M.D. & Steve Goldner, J.D.: Cannabis – the latest science on CBD & THC", actual_length: "2h 11min", url: "http://hwcdn.libsyn.com/p/d/3/a/d3a34a86d6b39f07/EP.81_-_Steve_Goldner_and_Debra_Kimless_FINAL.mp3?c_id=58260380&cs_id=58260380&destination_id=713489&expiration=1575275657&hwt=413be044f175f6310f646a966777170f", category: "Medical Science, Health", age_group: "Young Adults, Adults", duration: "Long", description: "In this episode, Dr. Debra Kimless and Steve Goldner share their knowledge on the science, policy, and market evolution of medicinal cannabis. We start with the differences between THC and CBD, how they work in the body, and how they act on the brain. We discuss the many potential benefits of using CBD, THC, hemp in the various forms of administration (smoking, vaping, edibles, oils, etc.) as well as some of the safety issues including the recent uptick in incidents of hospitalization and death linked to vaping. Debra and Steve are both involved with the company, Pure Green—Debra the Chief Medical Officer and Steve the founder and CEO—whose aim is to create the safest, most efficacious form of delivery of cannabis. Their bigger mission is to shift the perception of the cannabis plant, garner acceptance of its medicinal benefits, and ultimately get it descheduled on a federal level so more people can access cannabis for a range of chronic ailments.")

Podcast.create(educator_profile_id: 4, podcast_title: "The Peter Attia Drive", date: "December 10th 2019", podcast_photo: "https://cachedimages.podchaser.com/x200/aHR0cDovL3N0YXRpYy5saWJzeW4uY29tL3AvYXNzZXRzL2IvNy84L2YvYjc4ZmM1MDgyNmNhNDQ3Yy9FUC44MV8tX1N0ZXZlX0dvbGRuZXJfYW5kX0RlYnJhX0tpbWxlc3NfRklOQUwucG5n/aHR0cHM6Ly93d3cucG9kY2hhc2VyLmNvbS9pbWFnZXMvbWlzc2luZy1pbWFnZS5wbmc%3D", episode_no: "32", episode_name: "#32 - Siddhartha Mukherjee, M.D., Ph.D.: new frontiers in cancer therapy, medicine, and the writing process", actual_length: "1h 5m", url: "http://hwcdn.libsyn.com/p/6/2/6/626364b459886d18/EP.32_-_Siddhartha_Mukherjee_FINAL.mp3?c_id=28192505&cs_id=28192505&destination_id=713489&expiration=1575471571&hwt=062b3f6fd450fbd9cee39e45f875c840", category: "Medical Science, Health, Research", age_group: "Young Adults, Adults", duration: "Long", description: "In this episode, Siddhartha Mukherjee, oncologist, researcher, and author of the Pulitzer Prize-winning book “The Emperor of All Maladies: A Biography of Cancer,” discusses his writing process, his thoughts about medicine, cancer, immunotherapy, and his recent collaboration on a study combining a ketogenic diet with a drug in mice that provided remarkable and encouraging results.")

EducatorProfile.create(name: "Molly Bloom", description: "Molly Bloom is a digital producer for MPR News. She is also the host and co-producer of Brains On! a science podcast for kids and curious adults.", photo_url: "https://cachedimages.podchaser.com/300x300/aHR0cHM6Ly9jcmVhdG9yLWltYWdlcy5wb2RjaGFzZXIuY29tL2I5OTgxY2YyNTQ5NTllMDllMGE3ZDMxZGY2OWU2Yjc5LnBuZw%3D%3D/aHR0cHM6Ly93d3cucG9kY2hhc2VyLmNvbS9pbWFnZXMvbWlzc2luZy1pbWFnZS5wbmc%3D")

Podcast.create(educator_profile_id: 5, podcast_title: "Brains On!", date: "March 14th 2017", podcast_photo: "https://cachedimages.podchaser.com/300x300/aHR0cHM6Ly9pbWcuYXBtY2RuLm9yZy80MzNlYzc3Njc1MDQ1YWZlNTcwMTFkNTY3MWJhN2Y4YzAwMDAwNjQ4L3VuY3JvcHBlZC84NDQxNjgtMjAxODA1MjktYnJhaW5zLW9uLXBvZGNhc3QtbG9nby1tYXktMjAxOC5wbmc%3D/aHR0cHM6Ly93d3cucG9kY2hhc2VyLmNvbS9pbWFnZXMvbWlzc2luZy1pbWFnZS5wbmc%3D", episode_no: "100", episode_name: "Why is the ocean salty?", actual_length: "16m 12s", url: "https://play.podtrac.com/APM-BrainsOn/play.publicradio.org/itunes/o/podcast/minnesota/podcasts/brains_on/2017/03/brainson_20170314_71_20170314_64.mp3", category: "Just For Kids, Curiosity, Exploration, Family", age_group: "Kids, Teens", duration: "Short", description: "If you’ve ever been the ocean, you’ve tasted that salt. But where does it come from? And why aren’t lakes and rivers salty too? A sea shanty is probably the best way to explain, right?")

EducatorProfile.create(name: "Lindsay Patterson", description: "Lindsay Patterson is the creator and co-host of the Tumble podcast ", photo_url: "https://cachedimages.podchaser.com/300x300/aHR0cHM6Ly9jcmVhdG9yLWltYWdlcy5wb2RjaGFzZXIuY29tLzZjNjEzYTg1ODRhMTQ0ODIyN2Y1NzA4YTVhOTZlNzRmLnBuZw%3D%3D/aHR0cHM6Ly93d3cucG9kY2hhc2VyLmNvbS9pbWFnZXMvbWlzc2luZy1pbWFnZS5wbmc%3D")

Podcast.create(educator_profile_id: 6, podcast_title: "Tumble Science Podcast for Kids", date: "October 4th 2019", podcast_photo: "https://cachedimages.podchaser.com/300x300/aHR0cHM6Ly9mLnByeHUub3JnLzEyMi9pbWFnZXMvOGE4NDc4ZGMtOGViZC00ZDJhLTg4YTctMTQ0MzNlODFjMzQxL2JmYmZkOWUzM2IyMWI2NGM2NGI0ZjczMmY4MTY0MGMyMDViYzNhZjM2MTI3MTBhMjYzMzBiMWJiZmYwODdiYTFhZDIyZmY4YTQwNDk4Y2IzYjUwY2I4Njk3MGY4NmFkMzUwYjIwM2E5NGMxN2VkOWMxMTVkOTgzYTc2OGU0OWIwLmpwZWc%3D/aHR0cHM6Ly93d3cucG9kY2hhc2VyLmNvbS9pbWFnZXMvbWlzc2luZy1pbWFnZS5wbmc%3D", episode_no: "201", episode_name: "The Tale of the Hungry Koala", actual_length: "22m 59s", url: "https://play.podtrac.com/APM-BrainsOn/play.publicradio.org/itunes/o/podcast/minnesota/podcasts/brains_on/2017/03/brainson_20170314_71_20170314_64.mp3", category: "Just For Kids, Curiosity, Exploration, Family, Animals", age_group: "Kids, Teens", duration: "Short", description: "How does a koala eat eucalyptus leaves? Eucalyptus is toxic to most animals, but they’re a koala’s only food. In this episode, we look past the cuddliness to discover how koalas manage to chow down on the Australian tree species. Biologist Michaela Blyton shares the story of how she convinced some extremely picky koalas to try new foods in the midst of a conservation crisis. Spoiler alert: It involves starting a koala hotel, and inventing a pill with an unusual ingredient.")


EducatorProfile.create(name: "Nick Loper", description: "Nick Loper is an entrepreneur, marketer, skier, author, business nerd, seattle sports fan, parrothead, podcaster and host of The Side Hustle Show.", photo_url: "https://cachedimages.podchaser.com/300x300/aHR0cHM6Ly9jcmVhdG9yLWltYWdlcy5wb2RjaGFzZXIuY29tLzY2MzE0Y2Y5ZmQyNGI0NjhkY2U5MWFjMTBhNDM4OWYzLnBuZw%3D%3D/aHR0cHM6Ly93d3cucG9kY2hhc2VyLmNvbS9pbWFnZXMvbWlzc2luZy1pbWFnZS5wbmc%3D")


Podcast.create(educator_profile_id: 7, podcast_title: "The Side Hustle Show", date: "October 19th 2017", podcast_photo: "https://cachedimages.podchaser.com/300x300/aHR0cDovL3N0YXRpYy5saWJzeW4uY29tL3AvYXNzZXRzLzMvYy82LzcvM2M2NzEyN2QzYjJjZGI5OS9TaWRlX0h1c3RsZV9TaG93X2NvdmVyX2FydF8yMDE3LmpwZw%3D%3D/aHR0cHM6Ly93d3cucG9kY2hhc2VyLmNvbS9pbWFnZXMvbWlzc2luZy1pbWFnZS5wbmc%3D", episode_no: "253", episode_name: "253: Your Escape Plan: How to Make Early “Retirement” a Reality", actual_length: "22m 59s", url: "https://play.podtrac.com/APM-BrainsOn/play.publicradio.org/itunes/o/podcast/minnesota/podcasts/brains_on/2017/03/brainson_20170314_71_20170314_64.mp3", category: "Entrepreneruship, Inspiration, Finance", age_group: "Young Adults, Adults", duration: "Long", description: "Quit my job? “That’s stupid,” Kim Anderson said.
    But she eventually did, and it turned out to be a really smart move. Together with her husband Cressel, they paid off $93k in debt in less than 2 years, setting themselves up for a life of “financial flexibility.”
    They did it through a combination of conscious spending, creative side hustles, and having a clear goal in mind. And perhaps what’s more exciting is what that new time freedom has allowed: starting a family, starting new businesses, and most recently even “retiring” Cressel from his engineering job.
    In this inspiring episode, Kim and Cressel break down their path to financial freedom, which I think will get your gears turning on how to do the same.")


EducatorProfile.create(name: "Kelton Reid", description: "Podcast Producer, Writer", photo_url: "https://cachedimages.podchaser.com/300x300/aHR0cHM6Ly9jcmVhdG9yLWltYWdlcy5wb2RjaGFzZXIuY29tLzY4MTRhMzI5NWJmMzE3ZDdlMDg0ZjY0MTNmM2RlMzViLnBuZw%3D%3D/aHR0cHM6Ly93d3cucG9kY2hhc2VyLmNvbS9pbWFnZXMvbWlzc2luZy1pbWFnZS5wbmc%3D")

Podcast.create(educator_profile_id: 8, podcast_title: "The Writer Files", date: "July 18th 2017", podcast_photo: "https://cachedimages.podchaser.com/300x300/aHR0cHM6Ly9zMy5hbWF6b25hd3MuY29tL3BvZGNhc3RzLmltYWdlcy5wb2RjaGFzZXIuY29tLzEyMzM0ZDM2NTg2NmVmZGY2YTZjMzVkNjZmYTVkYWJhX21lZGl1bS5wbmc%3D/aHR0cHM6Ly93d3cucG9kY2hhc2VyLmNvbS9pbWFnZXMvbWlzc2luZy1pbWFnZS5wbmc%3D", episode_no: "173", episode_name: "Busting the Myth of the Starving Artist with Jeff Goins: Part One", actual_length: "27m 20s", url: "https://rainmaker.fm/wp-content/uploads/2017/07/writer-106.mp3", category: "Creative Writing, Exploration", age_group: "Teens, Young Adults, Adults", duration: "Medium", description: "In addition to being an entrepreneur and speaker, Jeff is a writing and creativity consultant, and his popular blog, Goins, Writer, offers free tips about the writing life.
    His podcast, The Portfolio Life, delves into many of the same topics via interviews with entrepreneurs and writers aimed squarely at helping listeners pursue work that matters.
    On Jeff’s last visit to the show in 2015, we talked about his bestselling book, The Art of Work, and how to think like a professional writer.
    His latest, Real Artists Don’t Starve, “… dismantles the myth that being creative is a hindrance to success …,” and bestselling author Daniel Pink said of the book, “Every entrepreneur, writer, and artist should read this book and take notes.”
    Writers, I think you’re going to like this one.")

EducatorProfile.create(name: "Roman Mars", description: "Roman Mars is an American radio producer. He is the host and producer of 99% Invisible and a founder of the podcast collective Radiotopia.", photo_url: "https://cachedimages.podchaser.com/300x300/aHR0cHM6Ly9jcmVhdG9yLWltYWdlcy5wb2RjaGFzZXIuY29tLzVkZjBmYTM0ODdiNzUwNDE4YjM0ZmJmODI3NzY2ZjczLmpwZWc%3D/aHR0cHM6Ly93d3cucG9kY2hhc2VyLmNvbS9pbWFnZXMvbWlzc2luZy1pbWFnZS5wbmc%3D")

Podcast.create(educator_profile_id: 9, podcast_title: "99% Invisible", date: "November 19th 2019", podcast_photo: "https://cachedimages.podchaser.com/300x300/aHR0cHM6Ly9mLnByeHUub3JnLzk2L2ltYWdlcy9hMmRmYTg4ZS1jYmU5LTRhNDEtYjFhNi03MjY5NGU2MGU3ZmQvOTktMTQwMC5wbmc%3D/aHR0cHM6Ly93d3cucG9kY2hhc2VyLmNvbS9pbWFnZXMvbWlzc2luZy1pbWFnZS5wbmc%3D", episode_no: "379", episode_name: "Cautionary Tales", actual_length: "34m 31s", url: "https://dts.podtrac.com/redirect.mp3/media.blubrry.com/99percentinvisible/dovetail.prxu.org/96/d44f6a14-e393-4e29-918d-a7d160d95772/379_Cautionary_Tales_pt01.mp3", category: "Design, Art, Creativity", age_group: "Young Adults, Adults", duration: "Medium", description: "Galileo tried to teach us that adding more and more layers to a system intended to avert disaster often makes catastrophe all the more likely. His basic lesson has been ignored in nuclear power plants, financial markets and at the Oscars... all resulting in chaos. At the 2017 Academy Awards, Warren Beatty and Faye Dunaway famously handed the Best Picture Oscar to the wrong movie. In this episode of Cautionary Tales, Tim Harford takes us through all of the poor design choices leading into the infamous La La Land/Moonlight debacle, and how it could have been prevented.")

EducatorProfile.create(name: "Elizabeth Gilbert", description: "Elizabeth M. Gilbert is an American author, essayist, short story writer, biographer, novelist, and memoirist. She is the host of the Good Life Project podcast.", photo_url: "https://cachedimages.podchaser.com/300x300/aHR0cHM6Ly9jcmVhdG9yLWltYWdlcy5wb2RjaGFzZXIuY29tL2FmYTQ5OWQyYWZjZTZkZjcyMjFiZmEwMTk5YTg1ZGZiLmpwZWc%3D/aHR0cHM6Ly93d3cucG9kY2hhc2VyLmNvbS9pbWFnZXMvbWlzc2luZy1pbWFnZS5wbmc%3D")

Podcast.create(educator_profile_id: 10, podcast_title: "Good Life Project", date: "November 21st 2019", podcast_photo: "https://cachedimages.podchaser.com/300x300/aHR0cHM6Ly9jb250ZW50LnByb2R1Y3Rpb24uY2RuLmFydDE5LmNvbS9pbWFnZXMvZjUvYjYvZWYvZDUvZjViNmVmZDUtMjhiYy00NDc1LTg4YTAtMmZhMTQ4MDBiZDZkL2FlOWU3Njc4YzFiNDQ1MzA0NjUwOWQ3OTQ3ZTE3MDIyMGEwNDZiN2JmYTk3OTZmNWQ0NDc5NTY0MWRhMzc1MDYyOTJjY2U5ZDY3YjBmMzhmYTQ1ZGEzZjI2NDI5NTA2NTFhNWVmYjM3ZDFmODA3OWMxYmMxOGU4YWNlZjVkNWZmLmpwZWc%3D/aHR0cHM6Ly93d3cucG9kY2hhc2VyLmNvbS9pbWFnZXMvbWlzc2luZy1pbWFnZS5wbmc%3D", episode_no: "279", episode_name: "You Are Worth It | Kyle Carpenter", actual_length: "1h 18m", url: "https://content.production.cdn.art19.com/validation=1575554421,a596f6ce-2eeb-5313-ab20-29918a0b6bf0,xNf89OIqcV5AVMwPu_mCCNQKY6s/episodes/eb5b6ccb-d9d7-4b57-a461-4af375bb255b/a0a6de3f3b4b309d5ba9790347b2941ed546efc003e57a829e8641a73292ebe7b25b5e4026f8085b822993e2d1c310630e6078648d99e73fff470d799fac4b2d/Kyle%20Carpenter%20BEST.mp3", category: "Inspiration, Creativity, Self-Help", age_group: "Teens, Young Adults, Adults", duration: "Long", description: "When a stranger thanks Kyle Carpenter for his service as a U.S. Marine, his automatic reply is, you are worth it. Enlisting in the Marine Corps in 2009, he served for more than a year in Helmand Province, Afghanistan as part of Operation Enduring Freedom, when he and his fellow Marines came under attack. In an act of extraordinary sacrifice, Carpenter threw himself on a grenade to save those around him. Regaining consciousness briefly and realizing the extent of his injuries, as he drifted back into unconsciousness, he was sure he was taking his last breath. Thankfully, he was wrong. Kyle woke up 5 weeks later at Walter Reed hospital, where he would learn that large parts of his face, head and right arm had been destroyed and needed to be reconstructed and he'd have a long road to recovery. Still, he was alive and grateful. Now the youngest living recipient of the US military’s highest honor, the Medal of Honor, in today's conversation, Kyle shares his extraordinary journey, his deep sense of service, love of people, family and his fellow Marines, what happened on that fateful day, along with his years-long road to rehabilitation, not just physically, but emotionally and spiritually, his reclamation of life and hope, and the legacy of kindness and service he is working to build and his desire to help inspire people to embrace life. Much of this is also documented in his moving memoir, You Are Worth It.")

EducatorProfile.create(name: "Jen Simmons", description: "Jen Simmons is the host and executive producer of The Web Ahead, winner of the 2015 Net Award for Podcast of the Year.", photo_url: "https://cachedimages.podchaser.com/300x300/aHR0cHM6Ly9jcmVhdG9yLWltYWdlcy5wb2RjaGFzZXIuY29tL2E3MjQ1NmQ3NmI0MWUzNzcyMzkxMjllNzY1NzY5NzJlLmpwZWc%3D/aHR0cHM6Ly93d3cucG9kY2hhc2VyLmNvbS9pbWFnZXMvbWlzc2luZy1pbWFnZS5wbmc%3D")

Podcast.create(educator_profile_id: 11, podcast_title: "The Web Ahead", date: "November 21st 2019", podcast_photo: "https://cachedimages.podchaser.com/300x300/aHR0cDovL2ljZWJveC41Ynk1LnR2L2ltYWdlcy9icm9hZGNhc3RzLzI2L2NvdmVyLmpwZw%3D%3D/aHR0cHM6Ly93d3cucG9kY2hhc2VyLmNvbS9pbWFnZXMvbWlzc2luZy1pbWFnZS5wbmc%3D", episode_no: "105", episode_name: "105: Progressive Enhancement with Aaron Gustafson", actual_length: "1h 21m", url: "http://cdn.5by5.tv/audio/broadcasts/webahead/2015/webahead-105.mp3", category: "Technology, Software, Creativity, Web", age_group: "Young Adults, Adults", duration: "Long", description: "Progressive Enhancement is a core principle of the web. But these days it seems a lot of folks don't quite understand what it's about. Aaron Gustafson joins Jen Simmons to break it down, and explain why and how your website should be built using the principles of Progressive Enhancement.")

